version: '3.8'
services:
  app:
    # image: myimage
    build: .
    ports:
      - "5000:5000"
    environment:
      - GREETING=Please Hire me.

  proxy:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - app